In [1]:
from datascience import *
import numpy as np

## Review of Numbers ##

In [5]:
4 * 5 # int

20

In [6]:
4/5 # float

0.8

In [7]:
5/5

1.0

In [8]:
type(4/5)

float

In [9]:
type(5)

int

In [10]:
10/3

3.3333333333333335

In [11]:
int(4/5)

0

In [12]:
int(6/3)

2

In [13]:
int(7/2)

3

## Review of Strings ##

In [14]:
"data 8"

'data 8'

In [15]:
data 8

SyntaxError: invalid syntax (2808813228.py, line 1)

In [16]:
data

NameError: name 'data' is not defined

In [17]:
'data' + '8'

'data8'

In [18]:
'data ' + '8'

'data 8'

In [19]:
'data'+' '+'8'

'data 8'

In [20]:
'data'*5

'datadatadatadatadata'

In [21]:
'data'*5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [22]:
'data'+5

TypeError: can only concatenate str (not "int") to str

In [24]:
'data' + str(5)

'data5'

In [25]:
int(3.2)

3

In [27]:
float(3.2)

3.2

In [26]:
int('3.2')

ValueError: invalid literal for int() with base 10: '3.2'

In [28]:
type(3.2)

float

## Review of Tables ##

In [2]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [29]:
skyscrapers.select('name', 'height')

name                              | height
One World Trade Center            | 541.3
Willis Tower                      | 442.14
432 Park Avenue                   | 425.5
Trump International Hotel & Tower | 423.22
Empire State Building             | 381
Bank of America Tower             | 365.8
Stratosphere Tower                | 350.22
Aon Center                        | 346.26
John Hancock Center               | 343.69
WITI TV Tower                     | 329
... (190 rows omitted)

In [30]:
skyscrapers.select('height',
            'name')

height | name
541.3  | One World Trade Center
442.14 | Willis Tower
425.5  | 432 Park Avenue
423.22 | Trump International Hotel & Tower
381    | Empire State Building
365.8  | Bank of America Tower
350.22 | Stratosphere Tower
346.26 | Aon Center
343.69 | John Hancock Center
329    | WITI TV Tower
... (190 rows omitted)

In [31]:
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [32]:
new_table = skyscrapers.select('name', 'height')
new_table

name                              | height
One World Trade Center            | 541.3
Willis Tower                      | 442.14
432 Park Avenue                   | 425.5
Trump International Hotel & Tower | 423.22
Empire State Building             | 381
Bank of America Tower             | 365.8
Stratosphere Tower                | 350.22
Aon Center                        | 346.26
John Hancock Center               | 343.69
WITI TV Tower                     | 329
... (190 rows omitted)

In [33]:
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [34]:
skyscrapers.drop('material')

name                              | city          | height | completed
One World Trade Center            | New York City | 541.3  | 2014
Willis Tower                      | Chicago       | 442.14 | 1974
432 Park Avenue                   | New York City | 425.5  | 2015
Trump International Hotel & Tower | Chicago       | 423.22 | 2009
Empire State Building             | New York City | 381    | 1931
Bank of America Tower             | New York City | 365.8  | 2009
Stratosphere Tower                | Las Vegas     | 350.22 | 1996
Aon Center                        | Chicago       | 346.26 | 1973
John Hancock Center               | Chicago       | 343.69 | 1969
WITI TV Tower                     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [35]:
skyscrapers.drop('material', 'height')

name                              | city          | completed
One World Trade Center            | New York City | 2014
Willis Tower                      | Chicago       | 1974
432 Park Avenue                   | New York City | 2015
Trump International Hotel & Tower | Chicago       | 2009
Empire State Building             | New York City | 1931
Bank of America Tower             | New York City | 2009
Stratosphere Tower                | Las Vegas     | 1996
Aon Center                        | Chicago       | 1973
John Hancock Center               | Chicago       | 1969
WITI TV Tower                     | Shorewood     | 1962
... (190 rows omitted)

In [36]:
skyscrapers.where('city', 'San Francisco')

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009

In [37]:
skyscrapers.where('city', 'San Francisco').sort('height')

name                  | material  | city          | height | completed
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009
345 California Center | steel     | San Francisco | 211.84 | 1986
555 California Street | steel     | San Francisco | 237.44 | 1969
Transamerica Pyramid  | composite | San Francisco | 260    | 1972

In [38]:
sf_buildings = skyscrapers.where('city', 'San Francisco')
sf_buildings

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009

In [39]:
sf_buildings.sort('height')

name                  | material  | city          | height | completed
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009
345 California Center | steel     | San Francisco | 211.84 | 1986
555 California Street | steel     | San Francisco | 237.44 | 1969
Transamerica Pyramid  | composite | San Francisco | 260    | 1972

In [40]:
sf_buildings.sort('name')

name                  | material  | city          | height | completed
345 California Center | steel     | San Francisco | 211.84 | 1986
555 California Street | steel     | San Francisco | 237.44 | 1969
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009
Transamerica Pyramid  | composite | San Francisco | 260    | 1972

In [41]:
sf_buildings.sort('name', descending=True)

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986

In [42]:
 skyscrapers.where('city', 'San Francisco').sort('name', descending=True)

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986

In [43]:
 skyscrapers.where('city', 'San Francisco').sort('name', descending=True).drop('city')

name                  | material  | height | completed
Transamerica Pyramid  | composite | 260    | 1972
Millennium Tower      | concrete  | 196.6  | 2009
555 California Street | steel     | 237.44 | 1969
345 California Center | steel     | 211.84 | 1986

In [44]:
 skyscrapers.where('city', 'San Francisco').drop('city').sort('name', descending=True)

name                  | material  | height | completed
Transamerica Pyramid  | composite | 260    | 1972
Millennium Tower      | concrete  | 196.6  | 2009
555 California Street | steel     | 237.44 | 1969
345 California Center | steel     | 211.84 | 1986

## Types ##

In [45]:
type(45)

int

In [46]:
type(4.5)

float

In [47]:
type('4.5')

str

In [48]:
type(abs)

builtin_function_or_method

In [49]:
type(skyscrapers)

datascience.tables.Table

In [50]:
type(True)

bool

## Arrays ##

In [51]:
my_array = make_array(1, 2, 3, 4) # inside array, "things" need to be the same type

In [52]:
my_array

array([1, 2, 3, 4])

In [53]:
your_array = make_array(1, 2, 3.4)

In [54]:
your_array

array([1. , 2. , 3.4])

In [55]:
my_array * 2

array([2, 4, 6, 8])

In [56]:
my_array ** 2

array([ 1,  4,  9, 16])

In [57]:
your_array ** 2

array([ 1.  ,  4.  , 11.56])

In [58]:
my_array

array([1, 2, 3, 4])

In [59]:
result_array = your_array ** 2
result_array

array([ 1.  ,  4.  , 11.56])

In [60]:
your_array

array([1. , 2. , 3.4])

In [61]:
my_array.size

4

In [62]:
len(my_array) # second way to get length of array

4

In [63]:
my_array.sum()

10

In [64]:
sum(my_array) # second way to sum array

10

In [65]:
my_array.sum()/my_array.size

2.5

In [66]:
np.average(my_array)  # use numpy average function

2.5

In [67]:
type(my_array.item(0))

int

In [68]:
my_array.item(0) # indices start at 0

1

In [69]:
my_array.item(2)

3

In [70]:
type(your_array.item(0))

float

In [71]:
your_array.item(0)

1.0

In [72]:
my_array + your_array

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## Columns of Tables are Arrays ##

In [4]:
sf = skyscrapers.where('city', 'San Francisco')
sf

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009

In [73]:
sf.select('height')

height
260
237.44
211.84
196.6

In [74]:
sf.column('height')

array([260.        , 237.44000244, 211.83999634, 196.6000061 ])

In [75]:
type(sf.select('height'))

datascience.tables.Table

In [76]:
type(sf.column('height'))

numpy.ndarray